spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
          github:
            client-id:
            client-secret:
          facebook:
            client-id:
            client-secret:
