spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
          github:
            client-id: ofujasldkfjalsf
            client-secret: aldsjflaksdjfkl
          facebook:
            client-id: asldfjlaksfjlkasjfd
            client-secret: asldfjalskdfkjalk
